export interface AdminBookingTraveler {
    id: number;
    isPrimary: boolean;
    name: string;
    dateOfBirth: string;
    nationality: string;
    email: string;
    phone: string;
    countryOfResidence: string;
    isFirstVisit: string;
}

export interface AdminBookingDetail {
    id: number;
    reference: string;
    status: string;
    travelerName: string;
    email: string;
    preferredDate: string;
    travelerCount: number;
    receivedAt: string;
    adults: number;
    children: number;
    groupType: string;
    flexibility: string;
    season: string;
    durationDays: number;
    otherDestination: string;
    recommendDestinations: boolean;
    routePreference: string;
    destinations: string[];
    interests: string[];
    visaStatus: string;
    insuranceStatus: string;
    emergencyName: string;
    emergencyRelationship: string;
    emergencyPhone: string;
    dietary: string;
    dietaryDetails: string;
    medical: string;
    medicalDetails: string;
    contactMethod: string;
    specialRequests: string;
    accuracy: boolean;
    terms: boolean;
    privacy: boolean;
    marketing: boolean;
    wantsComplete: boolean;
    wantsGuide: boolean;
    guideCount: number | null;
    guideGender: string;
    wantsTransportation: boolean;
    wantsAccommodation: boolean;
    wantsAirport: boolean;
    wantsDomestic: boolean;
    guideLanguage: string;
    guideLanguages: string;
    guideLanguageOther: string;
    guideRequest: string;
    vehicle: string;
    transportCoverage: string;
    transportNotes: string;
    accommodationLevel: string;
    roomPreference: string;
    roomCount: number | null;
    accommodationNotes: string;
    airportPickup: string;
    arrivalAssistance: string;
    arrivalDetailsLater: boolean;
    arrivalAirport: string;
    arrivalDate: string;
    arrivalTime: string;
    arrivalFlight: string;
    departureAssistance: string;
    departureDetailsLater: boolean;
    departureAirport: string;
    departureDate: string;
    departureTime: string;
    departureFlight: string;
    domesticPreference: string;
    travelers: AdminBookingTraveler[];
    documents: { issuingCountry: string; expiryDate: string }[];
    attachments?: {
        id: number;
        name: string;
        sizeLabel: string;
        uploadedBy: string;
        uploadedAt: string;
        downloadUrl: string;
    }[];
    history: { from: string | null; to: string; by: string; at: string }[];
    nextStatus: string | null;
    nextStatusLabel: string | null;
}
